#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'seqdiag==0.9.5','console_scripts','seqdiag'
__requires__ = 'seqdiag==0.9.5'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('seqdiag==0.9.5', 'console_scripts', 'seqdiag')()
    )
